### Project specific config ###
matrix:
  include:
    - os: linux
      language: python
      python: "2.7"
      env: ATOM_CHANNEL=stable

    - os: linux
      language: python
      python: "3.5"
      env: ATOM_CHANNEL=beta

    - os: osx
      language: generic
      env: ATOM_CHANNEL=stable
      before_install:
        - brew update
        - brew install python

install:
  - pip install pylint

before_script:
  - pylint --version

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
