language: generic
os:
  - osx

branches:
  only:
    - master
git:
  depth: 10

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - brew update
install:
  - brew install python
  - pip install pylint

before_script:
  - pylint --version
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
