### Project specific config ###
matrix:
  include:
    - os: linux
      language: python
      python: "2.7"
      env: ATOM_CHANNEL=stable

    - os: linux
      language: python
      python: "3.5"
      env: ATOM_CHANNEL=beta

install:
  - pip install pylint

before_script:
  - pylint --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
